import { ActivityStatusBadge } from "@/components/activities/ActivityStatusBadge";
import Link from "next/link";
import { GroupIcon } from "@/csmju";
import { getMyActivities } from "@/lib/api";
import { getSession, unwrap } from "@/lib/session";
import { SignedOut } from "@/components/layout/SignedOut";
import { RegistrationForm } from "@/components/ui/RegistrationForm";
import { applicationStatusLabels, formatActivityDate } from "@/lib/activity-presentation";

export default async function MyActivitiesPage() {
  const session = await getSession();
  if (!session) return <SignedOut />;
  const user = session.me;
  const { created, applications, registrations } = unwrap(await getMyActivities());
  const canCreate = session.canCreate;
  return <section className="flex min-w-0 flex-col gap-8 text-body-md leading-relaxed [&_h1]:font-display [&_h1]:text-headline-md md:[&_h1]:text-headline-lg [&_h2]:font-display [&_h2]:text-headline-md [&_h3]:font-display [&_h3]:text-body-lg [&_h3]:font-semibold">
    <div className="flex flex-wrap items-center justify-between gap-4">
      <div>
        <p className="text-label-md text-primary-container">MY ACTIVITY SPACE</p>
        <h1>กิจกรรมของฉัน</h1>
        <p className="text-body-md leading-relaxed text-on-surface-variant">สวัสดี {user.email} · จัดการทุกบทบาทของคุณได้ในที่เดียว</p>
      </div>
      <div className="flex flex-wrap items-center gap-2">
        {created.length > 0 && (
          <Link href="/my-activities/participants" className="inline-flex items-center justify-center min-h-11 rounded-lg border border-outline-variant px-4 py-2.5 text-label-md text-on-surface-variant transition-colors hover:bg-surface-variant/50 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-accent">
            <GroupIcon className="mr-2 h-5 w-5" /> ดูรายชื่อผู้สมัครทั้งหมด
          </Link>
        )}
        {canCreate && <Link href="/activities/create" className="btn-gradient inline-flex items-center justify-center min-h-11 rounded-lg px-4 py-2.5 text-label-md text-white shadow-md focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-accent disabled:opacity-50">+ สร้างกิจกรรมใหม่</Link>}
      </div>
    </div>
    <nav className="grid grid-cols-1 md:grid-cols-3 gap-6" aria-label="ข้ามไปส่วนกิจกรรม">
      {[{id:"registrations",label:"กิจกรรมที่เข้าร่วม",count:registrations.length,note:"ดูรายการและจัดการการลงทะเบียน",icon:"01"},{id:"created",label:"กิจกรรมที่ฉันสร้าง",count:created.length,note:"จัดการทีมงานและติดตามผล",icon:"02"},{id:"team",label:"ใบสมัครทีมงาน",count:applications.length,note:"ติดตามผลการคัดเลือก",icon:"03"}].map(item=><a key={item.id} href={"#"+item.id} className="min-w-0 rounded-xl border border-outline-variant/40 bg-surface-container-lowest shadow-sm p-6 [&_strong]:block [&_strong]:font-display [&_strong]:text-display-lg [&_strong]:tabular-nums [&_strong]:text-primary-container [&_strong]:my-2"><div className="flex justify-between items-center"><span>{item.label}</span><span className="inline-flex px-2.5 py-1 bg-primary-container/10 text-primary-container text-label-md rounded-full" aria-hidden="true">{item.icon}</span></div><strong>{String(item.count).padStart(2,"0")}</strong><p>{item.note} <span aria-hidden="true">↘</span></p></a>)}
    </nav>
    <div className="grid grid-cols-1 xl:grid-cols-4 gap-6 items-start [&>:first-child]:min-w-0 xl:[&>:first-child]:col-span-3"><div className="space-y-10">
      <section id="registrations" className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-4"><h2>กิจกรรมที่เข้าร่วม <span className="inline-flex px-2.5 py-1 bg-primary-container/10 text-primary-container text-label-md rounded-full">{registrations.length}</span></h2><Link href="/" className="text-primary">สำรวจกิจกรรม →</Link></div>
        {registrations.length===0 ? <div className="rounded-xl border border-dashed border-outline-variant bg-surface-container-lowest text-center p-8 [&_h3]:text-headline-md [&_h3]:mt-3 [&_h3]:mb-2 [&_p]:text-body-md [&_p]:text-on-surface-variant [&_p]:mb-6"><span className="inline-flex items-center justify-center w-12 h-12 rounded-lg bg-primary-container/10 text-primary-container text-headline-md" aria-hidden="true">＋</span><h3>ประสบการณ์ใหม่กำลังรอคุณอยู่</h3><p>คุณยังไม่ได้ลงทะเบียน ลองเลือกกิจกรรมที่สนใจ<br />แล้วกลับมาติดตามได้ที่หน้านี้</p><Link href="/" className="btn-gradient inline-flex items-center justify-center min-h-11 rounded-lg px-4 py-2.5 text-label-md text-white shadow-md focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-accent disabled:opacity-50">ค้นหากิจกรรมที่ใช่ →</Link></div> : registrations.map(r=><article className="min-w-0 rounded-xl border border-outline-variant/40 bg-surface-container-lowest shadow-sm p-6" key={r.id}><div className="flex flex-wrap items-center justify-between gap-4"><h3><Link href={"/activities/"+r.activityId}>{r.activity.title}</Link></h3><ActivityStatusBadge status={r.activity.status} /></div><p className="text-body-md leading-relaxed text-on-surface-variant">{formatActivityDate(r.activity.startAt)} · {r.activity.location}</p><div className="flex flex-wrap items-center justify-between gap-3 mt-6 pt-4 border-t border-outline-variant/40"><Link href={"/activities/"+r.activityId} className="inline-flex items-center justify-center min-h-11 rounded-lg border border-outline-variant px-4 py-2.5 text-label-md text-on-surface-variant transition-colors hover:bg-surface-variant/50 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-accent">ดูรายละเอียด →</Link>{["OPEN","FULL"].includes(r.activity.status) ? <RegistrationForm activityId={r.activityId} mode="cancel"/> : <p className="text-body-md leading-relaxed text-on-surface-variant">ปิดการยกเลิกลงทะเบียนแล้ว</p>}</div></article>)}
      </section>
      <section id="created" className="space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <h2>กิจกรรมที่ฉันสร้าง <span className="inline-flex px-2.5 py-1 bg-primary-container/10 text-primary-container text-label-md rounded-full">{created.length}</span></h2>
          {created.length > 0 && (
            <Link href="/my-activities/participants" className="text-primary text-sm">
              ดูรายชื่อผู้สมัครทั้งหมด →
            </Link>
          )}
        </div>
        {created.length===0 ? <div className="rounded-xl border border-dashed border-outline-variant bg-surface-container-lowest text-center p-8 [&_h3]:text-headline-md [&_h3]:mt-3 [&_h3]:mb-2 [&_p]:text-body-md [&_p]:text-on-surface-variant [&_p]:mb-6"><h3>ยังไม่มีกิจกรรมที่คุณสร้าง</h3>{canCreate ? <><p>สร้างกิจกรรมแล้วชวนเพื่อนมาร่วมทีมกัน</p><Link href="/activities/create" className="inline-flex items-center justify-center min-h-11 rounded-lg border border-outline-variant px-4 py-2.5 text-label-md text-on-surface-variant transition-colors hover:bg-surface-variant/50 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-accent">สร้างกิจกรรมแรก →</Link></> : <p>หัวหน้าห้องเป็นผู้สร้างกิจกรรม คุณสามารถเข้าร่วมหรือสมัครทีมงานได้</p>}</div> : created.map(a=><article key={a.id} className="min-w-0 rounded-xl border border-outline-variant/40 bg-surface-container-lowest shadow-sm p-6"><div className="flex flex-wrap items-center justify-between gap-4"><h3><Link href={"/activities/"+a.id}>{a.title}</Link></h3><ActivityStatusBadge status={a.status} /></div><p className="text-body-md leading-relaxed text-on-surface-variant">{formatActivityDate(a.startAt)} · {a.location}</p><div className="flex flex-wrap items-center justify-between gap-3 mt-6 pt-4 border-t border-outline-variant/40"><span className="text-body-md leading-relaxed text-on-surface-variant">ผู้เข้าร่วม <strong className="text-on-surface">{a.currentParticipants} / {a.maxParticipants}</strong> คน</span><div className="flex flex-wrap gap-2"><Link href={"/organizer/"+a.id+"/summary"} className="inline-flex items-center justify-center min-h-11 rounded-lg border border-outline-variant px-4 py-2.5 text-label-md text-on-surface-variant transition-colors hover:bg-surface-variant/50 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-accent">สรุปผลประเมิน</Link><Link href={"/organizer/"+a.id+"/manage"} className="btn-gradient inline-flex items-center justify-center min-h-11 rounded-lg px-4 py-2.5 text-label-md text-white shadow-md focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-accent disabled:opacity-50">จัดการกิจกรรม →</Link></div></div></article>)}
      </section>
      <section id="team" className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-4"><h2>ใบสมัครทีมงาน <span className="inline-flex px-2.5 py-1 bg-primary-container/10 text-primary-container text-label-md rounded-full">{applications.length}</span></h2></div>{applications.length===0 ? <div className="rounded-xl border border-dashed border-outline-variant bg-surface-container-lowest text-center p-8 [&_h3]:text-headline-md [&_h3]:mt-3 [&_h3]:mb-2 [&_p]:text-body-md [&_p]:text-on-surface-variant [&_p]:mb-6"><h3>มาร่วมสร้างกิจกรรมด้วยกัน</h3><p>สมัครตำแหน่งทีมงานจากหน้ารายละเอียดกิจกรรมที่สนใจ</p><Link href="/" className="inline-flex items-center justify-center min-h-11 rounded-lg border border-outline-variant px-4 py-2.5 text-label-md text-on-surface-variant transition-colors hover:bg-surface-variant/50 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-accent">ดูกิจกรรมทั้งหมด →</Link></div> : applications.map(app=>{const { activity, role } = app;return <article key={app.id} className="min-w-0 rounded-xl border border-outline-variant/40 bg-surface-container-lowest shadow-sm p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-label-md text-primary-container">{role?.roleName ?? "ไม่ระบุตำแหน่ง"}</p><h3>{activity?.title ?? "ไม่พบกิจกรรม"}</h3></div><span className="inline-flex items-center gap-2 px-2.5 py-1 rounded-full text-label-sm bg-primary-container/10 text-primary-container">{applicationStatusLabels[app.status]}</span></div>{activity && <Link className="text-primary inline-block mt-4" href={"/activities/"+activity.id}>ดูรายละเอียดกิจกรรม →</Link>}</article>;})}</section>
    </div><aside className="hidden lg:block p-6 rounded-xl bg-primary-container/10 [&_ol]:grid [&_ol]:gap-6 [&_li>strong]:block [&_li>span]:block"><p className="text-label-md text-primary-container">พื้นที่ของทุกบทบาท</p><h2>หนึ่งคน<br />หลายประสบการณ์</h2><p>หัวหน้าห้องสร้างและจัดการกิจกรรม นักศึกษาทุกคนเข้าร่วมหรือสมัครเป็นทีมงานได้</p><ol><li><strong>เลือกกิจกรรมที่สนใจ</strong><span>ลงทะเบียนจากหน้ารายละเอียด</span></li><li><strong>ร่วมเป็นส่วนหนึ่งของทีม</strong><span>สมัครตำแหน่งที่อยากลอง</span></li><li><strong>ส่งต่อสิ่งที่ได้เรียนรู้</strong><span>ประเมินเมื่อกิจกรรมจบ เพื่อช่วยพัฒนาครั้งต่อไป</span></li></ol></aside></div>
  </section>;
}
